### ISSUE TITLE
Add empty state for no filter results

### ISSUE THREAD

**Issue by dexterca** [MyPureCloud/openapi-explorer#9]
Match empty state for _No request selected_

<img width="314" alt="screen shot 2016-08-22 at 9 34 47 am" src="https://cloud.githubusercontent.com/assets/485903/17856503/e0c3c7d4-684b-11e6-937d-3f39000dddcd.png">

**Comment by KevinGlinski** [comment]
commit f7b80a4c53762ddfbff99323552a5ed39a3ed922
